In [1]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import RobustScaler, StandardScaler
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import SGDRegressor
from sklearn.linear_model import LinearRegression
import matplotlib.pylab as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV

In [2]:
diamantes = pd.read_csv('/Users/anadeondarza/Desktop/ironhack_data/Todo junto/Data/diamantes.csv')
diamantes = diamantes.drop('Unnamed: 0', axis=1)
diamantes

city  price  carat clarity color      cut  depth  table     x  \
0      Amsterdam   6216   1.00     VS2     G  Premium   61.6   54.0  6.49   
1      Amsterdam    675   0.30     VS2     G  Premium   60.6   60.0  4.34   
2      Amsterdam   1841   0.62     VS2     G  Premium   61.1   59.0  5.56   
3      Amsterdam    720   0.32     VS2     G  Premium   60.2   57.0  4.45   
4      Amsterdam   8874   1.39     VS2     G  Premium   62.0   56.0  7.18   
...          ...    ...    ...     ...   ...      ...    ...    ...   ...   
40450    Antwerp   2211   0.47      IF     D     Fair   60.6   60.0  5.09   
40451     Zurich   5460   1.50      I1     D     Fair   64.7   62.0  7.19   
40452   Kimberly   2491   0.91      I1     D     Fair   66.2   57.0  6.00   
40453      Surat  15964   3.40      I1     D     Fair   66.8   52.0  9.42   
40454    Antwerp   5617   1.70      I1     D     Fair   64.7   56.0  7.46   

          y     z  
0      6.46  3.99  
1      4.30  2.62  
2      5.50  3.38  
3      4.42  2.67  
4      7.14  4.44  
...     ...   ...  
40450  4.98  3.05  
40451  7.04  4.60  
40452  5.94  3.95  
40453  9.34  6.27  
40454  7.37  4.80  

[40455 rows x 11 columns]

In [3]:
diamantes.rename(columns={'price':'target'},
               inplace=True)

In [4]:
y = diamantes.target
y

0         6216
1          675
2         1841
3          720
4         8874
         ...  
40450     2211
40451     5460
40452     2491
40453    15964
40454     5617
Name: target, Length: 40455, dtype: int64

In [5]:
diamantes["Volumen"] = diamantes['x']*diamantes['y']*diamantes['z']
diamantes

city  target  carat clarity color      cut  depth  table     x  \
0      Amsterdam    6216   1.00     VS2     G  Premium   61.6   54.0  6.49   
1      Amsterdam     675   0.30     VS2     G  Premium   60.6   60.0  4.34   
2      Amsterdam    1841   0.62     VS2     G  Premium   61.1   59.0  5.56   
3      Amsterdam     720   0.32     VS2     G  Premium   60.2   57.0  4.45   
4      Amsterdam    8874   1.39     VS2     G  Premium   62.0   56.0  7.18   
...          ...     ...    ...     ...   ...      ...    ...    ...   ...   
40450    Antwerp    2211   0.47      IF     D     Fair   60.6   60.0  5.09   
40451     Zurich    5460   1.50      I1     D     Fair   64.7   62.0  7.19   
40452   Kimberly    2491   0.91      I1     D     Fair   66.2   57.0  6.00   
40453      Surat   15964   3.40      I1     D     Fair   66.8   52.0  9.42   
40454    Antwerp    5617   1.70      I1     D     Fair   64.7   56.0  7.46   

          y     z     Volumen  
0      6.46  3.99  167.282346  
1      4.30  2.62   48.894440  
2      5.50  3.38  103.360400  
3      4.42  2.67   52.516230  
4      7.14  4.44  227.617488  
...     ...   ...         ...  
40450  4.98  3.05   77.312010  
40451  7.04  4.60  232.840960  
40452  5.94  3.95  140.778000  
40453  9.34  6.27  551.652156  
40454  7.37  4.80  263.904960  

[40455 rows x 12 columns]

In [6]:
diamantes_p1 = diamantes.drop(["target","cut", "color", "clarity","city","x","y","z"], axis = 1)
diamantes_p1

carat  depth  table     Volumen
0       1.00   61.6   54.0  167.282346
1       0.30   60.6   60.0   48.894440
2       0.62   61.1   59.0  103.360400
3       0.32   60.2   57.0   52.516230
4       1.39   62.0   56.0  227.617488
...      ...    ...    ...         ...
40450   0.47   60.6   60.0   77.312010
40451   1.50   64.7   62.0  232.840960
40452   0.91   66.2   57.0  140.778000
40453   3.40   66.8   52.0  551.652156
40454   1.70   64.7   56.0  263.904960

[40455 rows x 4 columns]

In [7]:
scaler = StandardScaler()
p1_scaler = scaler.fit_transform(diamantes_p1)
p1_scaler

array([[ 0.42540082, -0.10675463, -1.54292407,  0.47501459],
       [-1.04661509, -0.80522122,  1.1434334 , -1.02540837],
       [-0.37369353, -0.45598793,  0.69570715, -0.33511846],
       ...,
       [ 0.23614164,  3.10619169, -0.19974534,  0.13910418],
       [ 5.47231252,  3.52527165, -2.43837656,  5.34643522],
       [ 1.89741674,  2.0584918 , -0.64747158,  1.6995889 ]])

In [8]:
X1 = pd.DataFrame(p1_scaler)

In [9]:
X1

0         1         2         3
0      0.425401 -0.106755 -1.542924  0.475015
1     -1.046615 -0.805221  1.143433 -1.025408
2     -0.373694 -0.455988  0.695707 -0.335118
3     -1.004557 -1.084608 -0.199745 -0.979507
4      1.245524  0.172632 -0.647472  1.239689
...         ...       ...       ...       ...
40450 -0.689126 -0.805221  1.143433 -0.665250
40451  1.476841  2.058492  2.038886  1.305890
40452  0.236142  3.106192 -0.199745  0.139104
40453  5.472313  3.525272 -2.438377  5.346435
40454  1.897417  2.058492 -0.647472  1.699589

[40455 rows x 4 columns]

In [10]:
diamantes_p2 = diamantes[["cut", "color", "clarity","city"]]

In [11]:
diamantes_p2

cut color clarity       city
0      Premium     G     VS2  Amsterdam
1      Premium     G     VS2  Amsterdam
2      Premium     G     VS2  Amsterdam
3      Premium     G     VS2  Amsterdam
4      Premium     G     VS2  Amsterdam
...        ...   ...     ...        ...
40450     Fair     D      IF    Antwerp
40451     Fair     D      I1     Zurich
40452     Fair     D      I1   Kimberly
40453     Fair     D      I1      Surat
40454     Fair     D      I1    Antwerp

[40455 rows x 4 columns]

In [12]:
label_encoder = LabelEncoder()

In [13]:
for x in diamantes_p2.columns:
    diamantes_p2[x] = label_encoder.fit_transform(diamantes_p2[x])
diamantes_p2

/var/folders/nr/c9s62s617y19j9y8cd0wk75c0000gn/T/ipykernel_18857/1960983481.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  diamantes_p2[x] = label_encoder.fit_transform(diamantes_p2[x])


cut  color  clarity  city
0        3      3        5     0
1        3      3        5     0
2        3      3        5     0
3        3      3        5     0
4        3      3        5     0
...    ...    ...      ...   ...
40450    0      0        1     1
40451    0      0        0    12
40452    0      0        0     3
40453    0      0        0    10
40454    0      0        0     1

[40455 rows x 4 columns]

In [14]:
scaler = StandardScaler()
p2_scaler = scaler.fit_transform(diamantes_p2)
p2_scaler

array([[ 0.43492737,  0.23557324,  0.67238541, -1.51296444],
       [ 0.43492737,  0.23557324,  0.67238541, -1.51296444],
       [ 0.43492737,  0.23557324,  0.67238541, -1.51296444],
       ...,
       [-2.48104657, -1.52784785, -2.22618581, -0.72532786],
       [-2.48104657, -1.52784785, -2.22618581,  1.11249084],
       [-2.48104657, -1.52784785, -2.22618581, -1.25041891]])

In [15]:
X2 = pd.DataFrame(p2_scaler)

In [16]:
X2

0         1         2         3
0      0.434927  0.235573  0.672385 -1.512964
1      0.434927  0.235573  0.672385 -1.512964
2      0.434927  0.235573  0.672385 -1.512964
3      0.434927  0.235573  0.672385 -1.512964
4      0.434927  0.235573  0.672385 -1.512964
...         ...       ...       ...       ...
40450 -2.481047 -1.527848 -1.646472 -1.250419
40451 -2.481047 -1.527848 -2.226186  1.637582
40452 -2.481047 -1.527848 -2.226186 -0.725328
40453 -2.481047 -1.527848 -2.226186  1.112491
40454 -2.481047 -1.527848 -2.226186 -1.250419

[40455 rows x 4 columns]

In [17]:
X = pd.merge(X1, X2, left_index=True, right_index=True)
X

0_x       1_x       2_x       3_x       0_y       1_y       2_y  \
0      0.425401 -0.106755 -1.542924  0.475015  0.434927  0.235573  0.672385   
1     -1.046615 -0.805221  1.143433 -1.025408  0.434927  0.235573  0.672385   
2     -0.373694 -0.455988  0.695707 -0.335118  0.434927  0.235573  0.672385   
3     -1.004557 -1.084608 -0.199745 -0.979507  0.434927  0.235573  0.672385   
4      1.245524  0.172632 -0.647472  1.239689  0.434927  0.235573  0.672385   
...         ...       ...       ...       ...       ...       ...       ...   
40450 -0.689126 -0.805221  1.143433 -0.665250 -2.481047 -1.527848 -1.646472   
40451  1.476841  2.058492  2.038886  1.305890 -2.481047 -1.527848 -2.226186   
40452  0.236142  3.106192 -0.199745  0.139104 -2.481047 -1.527848 -2.226186   
40453  5.472313  3.525272 -2.438377  5.346435 -2.481047 -1.527848 -2.226186   
40454  1.897417  2.058492 -0.647472  1.699589 -2.481047 -1.527848 -2.226186   

            3_y  
0     -1.512964  
1     -1.512964  
2     -1.512964  
3     -1.512964  
4     -1.512964  
...         ...  
40450 -1.250419  
40451  1.637582  
40452 -0.725328  
40453  1.112491  
40454 -1.250419  

[40455 rows x 8 columns]

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(f"X_train: {X_train.shape}, X_test: {X_test.shape}, y_train: {y_train.shape}, y_test: {y_test.shape}")

X_train: (32364, 8), X_test: (8091, 8), y_train: (32364,), y_test: (8091,)


In [19]:
"""
param_grid = {
    'bootstrap': [True],
    'max_depth': [80, 90, 100, 110],
    'max_features': [2, 3],
    'min_samples_leaf': [3, 4, 5],
    'min_samples_split': [8, 10, 12],
    'n_estimators': [100, 200, 300, 1000]
}

rf = RandomForestRegressor()

grid_search = GridSearchCV(estimator = rf, param_grid = param_grid, 
                          cv = 3, n_jobs = -1, verbose = 2)

grid_search.fit(X_train, y_train)
grid_search.best_params_
"""


"\nparam_grid = {\n    'bootstrap': [True],\n    'max_depth': [80, 90, 100, 110],\n    'max_features': [2, 3],\n    'min_samples_leaf': [3, 4, 5],\n    'min_samples_split': [8, 10, 12],\n    'n_estimators': [100, 200, 300, 1000]\n}\n\nrf = RandomForestRegressor()\n\ngrid_search = GridSearchCV(estimator = rf, param_grid = param_grid, \n                          cv = 3, n_jobs = -1, verbose = 2)\n\ngrid_search.fit(X_train, y_train)\ngrid_search.best_params_\n"

In [20]:
"grid_search.best_params_"

'grid_search.best_params_'

In [21]:
model = RandomForestRegressor(random_state = 42,
                              n_estimators = 1000,
                             criterion = 'squared_error',
                             max_depth = None,
                             oob_score = True)

In [22]:
model.fit(X_train, y_train)

RandomForestRegressor(n_estimators=1000, oob_score=True, random_state=42)

In [23]:
predictions = model.predict(X_test)
predictions

array([ 725.688, 8263.094, 7639.069, ...,  507.577, 3530.943, 2433.026])

In [24]:
rmse = mean_squared_error(predictions, y_test, squared=False)
rmse

549.817422215626

In [ ]:
diamantes_predicts = pd.read_csv('/Users/anadeondarza/Desktop/ironhack_data/Todo junto/Data/diamonds_test.csv')
diamantes_predicts

In [ ]:
diamantes_predicts = diamantes_predicts.drop('id', axis=1)

In [ ]:
diamantes_predicts

In [ ]:
diamantes_predicts["Volumen"] = diamantes_predicts['x']*diamantes_predicts['y']*diamantes_predicts['z']
diamantes_predicts

In [ ]:
diamantes_predicts_p1 = diamantes_predicts.drop(["cut", "color", "clarity","city","x","y","z"], axis = 1)
diamantes_predicts_p1

In [ ]:
scaler = StandardScaler()
p1_scaler_predi = scaler.fit_transform(diamantes_predicts_p1)
p1_scaler_predi

In [ ]:
X1_predi = pd.DataFrame(p1_scaler_predi)

In [ ]:
diamantes_p2_predi = diamantes_predicts[["cut", "color", "clarity","city"]]

In [ ]:
diamantes_p2_predi

In [ ]:
for x in diamantes_p2_predi.columns:
    diamantes_p2_predi[x] = label_encoder.fit_transform(diamantes_p2_predi[x])
diamantes_p2_predi

In [ ]:
scaler = StandardScaler()
p2_scaler_predi = scaler.fit_transform(diamantes_p2_predi)
p2_scaler_predi

In [ ]:
X2_predi = pd.DataFrame(p2_scaler_predi)
X2_predi

In [ ]:
X = pd.merge(X1_predi, X2_predi, left_index=True, right_index=True)
X

In [ ]:
final = model.predict(X)
final

In [ ]:
final = pd.DataFrame(final).rename(columns = {0:'price'})
final.index.names = ['id']
final

In [ ]:
Entregado = final.to_csv('Entregado.csv')