In [1]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import RobustScaler, StandardScaler
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import SGDRegressor
from sklearn.linear_model import LinearRegression
import matplotlib.pylab as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV

In [2]:
diamantes = pd.read_csv('/Users/anadeondarza/Desktop/ironhack_data/Todo junto/Data/diamantes.csv')
diamantes = diamantes.drop('Unnamed: 0', axis=1)
diamantes

city  price  carat clarity color      cut  depth  table     x  \
0      Amsterdam   6216   1.00     VS2     G  Premium   61.6   54.0  6.49   
1      Amsterdam    675   0.30     VS2     G  Premium   60.6   60.0  4.34   
2      Amsterdam   1841   0.62     VS2     G  Premium   61.1   59.0  5.56   
3      Amsterdam    720   0.32     VS2     G  Premium   60.2   57.0  4.45   
4      Amsterdam   8874   1.39     VS2     G  Premium   62.0   56.0  7.18   
...          ...    ...    ...     ...   ...      ...    ...    ...   ...   
40450    Antwerp   2211   0.47      IF     D     Fair   60.6   60.0  5.09   
40451     Zurich   5460   1.50      I1     D     Fair   64.7   62.0  7.19   
40452   Kimberly   2491   0.91      I1     D     Fair   66.2   57.0  6.00   
40453      Surat  15964   3.40      I1     D     Fair   66.8   52.0  9.42   
40454    Antwerp   5617   1.70      I1     D     Fair   64.7   56.0  7.46   

          y     z  
0      6.46  3.99  
1      4.30  2.62  
2      5.50  3.38  
3      4.42  2.67  
4      7.14  4.44  
...     ...   ...  
40450  4.98  3.05  
40451  7.04  4.60  
40452  5.94  3.95  
40453  9.34  6.27  
40454  7.37  4.80  

[40455 rows x 11 columns]

In [3]:
diamantes.rename(columns={'price':'target'},
               inplace=True)

In [4]:
y = diamantes.target
y

0         6216
1          675
2         1841
3          720
4         8874
         ...  
40450     2211
40451     5460
40452     2491
40453    15964
40454     5617
Name: target, Length: 40455, dtype: int64

In [5]:
diamantes["Volumen"] = diamantes['x']*diamantes['y']*diamantes['z']
diamantes

city  target  carat clarity color      cut  depth  table     x  \
0      Amsterdam    6216   1.00     VS2     G  Premium   61.6   54.0  6.49   
1      Amsterdam     675   0.30     VS2     G  Premium   60.6   60.0  4.34   
2      Amsterdam    1841   0.62     VS2     G  Premium   61.1   59.0  5.56   
3      Amsterdam     720   0.32     VS2     G  Premium   60.2   57.0  4.45   
4      Amsterdam    8874   1.39     VS2     G  Premium   62.0   56.0  7.18   
...          ...     ...    ...     ...   ...      ...    ...    ...   ...   
40450    Antwerp    2211   0.47      IF     D     Fair   60.6   60.0  5.09   
40451     Zurich    5460   1.50      I1     D     Fair   64.7   62.0  7.19   
40452   Kimberly    2491   0.91      I1     D     Fair   66.2   57.0  6.00   
40453      Surat   15964   3.40      I1     D     Fair   66.8   52.0  9.42   
40454    Antwerp    5617   1.70      I1     D     Fair   64.7   56.0  7.46   

          y     z     Volumen  
0      6.46  3.99  167.282346  
1      4.30  2.62   48.894440  
2      5.50  3.38  103.360400  
3      4.42  2.67   52.516230  
4      7.14  4.44  227.617488  
...     ...   ...         ...  
40450  4.98  3.05   77.312010  
40451  7.04  4.60  232.840960  
40452  5.94  3.95  140.778000  
40453  9.34  6.27  551.652156  
40454  7.37  4.80  263.904960  

[40455 rows x 12 columns]

In [6]:
diamantes_p1 = diamantes.drop(["target","cut", "color", "clarity","city"], axis = 1)
diamantes_p1

carat  depth  table     x     y     z     Volumen
0       1.00   61.6   54.0  6.49  6.46  3.99  167.282346
1       0.30   60.6   60.0  4.34  4.30  2.62   48.894440
2       0.62   61.1   59.0  5.56  5.50  3.38  103.360400
3       0.32   60.2   57.0  4.45  4.42  2.67   52.516230
4       1.39   62.0   56.0  7.18  7.14  4.44  227.617488
...      ...    ...    ...   ...   ...   ...         ...
40450   0.47   60.6   60.0  5.09  4.98  3.05   77.312010
40451   1.50   64.7   62.0  7.19  7.04  4.60  232.840960
40452   0.91   66.2   57.0  6.00  5.94  3.95  140.778000
40453   3.40   66.8   52.0  9.42  9.34  6.27  551.652156
40454   1.70   64.7   56.0  7.46  7.37  4.80  263.904960

[40455 rows x 7 columns]

In [9]:
scaler = StandardScaler()
p1_scaler = scaler.fit_transform(diamantes_p1)
p1_scaler

array([[ 0.42540082, -0.10675463, -1.54292407, ...,  0.63418686,
         0.64965847,  0.47501459],
       [-1.04661509, -0.80522122,  1.1434334 , ..., -1.2495849 ,
        -1.31575886, -1.02540837],
       [-0.37369353, -0.45598793,  0.69570715, ..., -0.20304503,
        -0.22545435, -0.33511846],
       ...,
       [ 0.23614164,  3.10619169, -0.19974534, ...,  0.18068625,
         0.59227403,  0.13910418],
       [ 5.47231252,  3.52527165, -2.43837656, ...,  3.14588255,
         3.92057199,  5.34643522],
       [ 1.89741674,  2.0584918 , -0.64747158, ...,  1.42781293,
         1.81169354,  1.6995889 ]])

In [10]:
X1 = pd.DataFrame(p1_scaler)

In [11]:
X1

0         1         2         3         4         5         6
0      0.425401 -0.106755 -1.542924  0.676434  0.634187  0.649658  0.475015
1     -1.046615 -0.805221  1.143433 -1.235631 -1.249585 -1.315759 -1.025408
2     -0.373694 -0.455988  0.695707 -0.150646 -0.203045 -0.225454 -0.335118
3     -1.004557 -1.084608 -0.199745 -1.137805 -1.144931 -1.244028 -0.979507
4      1.245524  0.172632 -0.647472  1.290073  1.227226  1.295234  1.239689
...         ...       ...       ...       ...       ...       ...       ...
40450 -0.689126 -0.805221  1.143433 -0.568632 -0.656546 -0.698876 -0.665250
40451  1.476841  2.058492  2.038886  1.298967  1.140014  1.524771  1.305890
40452  0.236142  3.106192 -0.199745  0.240661  0.180686  0.592274  0.139104
40453  5.472313  3.525272 -2.438377  3.282178  3.145883  3.920572  5.346435
40454  1.897417  2.058492 -0.647472  1.539086  1.427813  1.811694  1.699589

[40455 rows x 7 columns]

In [18]:
diamantes_p2 = diamantes[["cut", "color", "clarity","city"]]

In [19]:
diamantes_p2

cut color clarity       city
0      Premium     G     VS2  Amsterdam
1      Premium     G     VS2  Amsterdam
2      Premium     G     VS2  Amsterdam
3      Premium     G     VS2  Amsterdam
4      Premium     G     VS2  Amsterdam
...        ...   ...     ...        ...
40450     Fair     D      IF    Antwerp
40451     Fair     D      I1     Zurich
40452     Fair     D      I1   Kimberly
40453     Fair     D      I1      Surat
40454     Fair     D      I1    Antwerp

[40455 rows x 4 columns]

In [20]:
cut_ = {'Very Good':3,'Ideal':4, 'Good':2, 'Premium':5, 'Fair':1}
diamantes_p2['cut'] = diamantes_p2['cut'].map(cut_)
diamantes_p2

/var/folders/nr/c9s62s617y19j9y8cd0wk75c0000gn/T/ipykernel_4527/1711579641.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  diamantes_p2['cut'] = diamantes_p2['cut'].map(cut_)


cut color clarity       city
0        5     G     VS2  Amsterdam
1        5     G     VS2  Amsterdam
2        5     G     VS2  Amsterdam
3        5     G     VS2  Amsterdam
4        5     G     VS2  Amsterdam
...    ...   ...     ...        ...
40450    1     D      IF    Antwerp
40451    1     D      I1     Zurich
40452    1     D      I1   Kimberly
40453    1     D      I1      Surat
40454    1     D      I1    Antwerp

[40455 rows x 4 columns]

In [21]:
color_ = {'D':2,'H':5, 'J':7, 'I':6, 'E':1, 'F':3, 'G':4}
diamantes_p2['color'] = diamantes_p2['color'].map(color_)
#diamantes_p2

/var/folders/nr/c9s62s617y19j9y8cd0wk75c0000gn/T/ipykernel_4527/3955782793.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  diamantes_p2['color'] = diamantes_p2['color'].map(color_)


In [22]:
clarity_ = {'SI2':8,'VVS2':2, 'VVS1':3, 'IF':1, 'SI1':6, 'I1':7, 'VS1':4, 'VS2':5 }
diamantes_p2['clarity'] = diamantes_p2['clarity'].map(clarity_)
diamantes_p2

/var/folders/nr/c9s62s617y19j9y8cd0wk75c0000gn/T/ipykernel_4527/1460536410.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  diamantes_p2['clarity'] = diamantes_p2['clarity'].map(clarity_)


cut  color  clarity       city
0        5      4        5  Amsterdam
1        5      4        5  Amsterdam
2        5      4        5  Amsterdam
3        5      4        5  Amsterdam
4        5      4        5  Amsterdam
...    ...    ...      ...        ...
40450    1      2        1    Antwerp
40451    1      2        7     Zurich
40452    1      2        7   Kimberly
40453    1      2        7      Surat
40454    1      2        7    Antwerp

[40455 rows x 4 columns]

In [23]:
city_ = {'Amsterdam':1,'Zurich':2, 'Las Vegas':3, 'New York City':4, 'Paris':5, 'Tel Aviv':6, 'Dubai':7, 'Kimberly':8, 'Surat':9,'Antwerp':10, 'Madrid':11, 'London':12, 'Luxembourg':13}
diamantes_p2['city'] = diamantes_p2['city'].map(city_)
diamantes_p2

/var/folders/nr/c9s62s617y19j9y8cd0wk75c0000gn/T/ipykernel_4527/2948679684.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  diamantes_p2['city'] = diamantes_p2['city'].map(city_)


cut  color  clarity  city
0        5      4        5     1
1        5      4        5     1
2        5      4        5     1
3        5      4        5     1
4        5      4        5     1
...    ...    ...      ...   ...
40450    1      2        1    10
40451    1      2        7     2
40452    1      2        7     8
40453    1      2        7     9
40454    1      2        7    10

[40455 rows x 4 columns]

In [24]:
#label_encoder = LabelEncoder()

In [25]:
#for x in diamantes_p2.columns:
#   diamantes_p2[x] = label_encoder.fit_transform(diamantes_p2[x])
#diamantes_p2

/var/folders/nr/c9s62s617y19j9y8cd0wk75c0000gn/T/ipykernel_4326/1960983481.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  diamantes_p2[x] = label_encoder.fit_transform(diamantes_p2[x])


cut  color  clarity  city
0        3      3        5     0
1        3      3        5     0
2        3      3        5     0
3        3      3        5     0
4        3      3        5     0
...    ...    ...      ...   ...
40450    0      0        1     1
40451    0      0        0    12
40452    0      0        0     3
40453    0      0        0    10
40454    0      0        0     1

[40455 rows x 4 columns]

In [24]:
scaler = StandardScaler()
p2_scaler = scaler.fit_transform(diamantes_p2)
p2_scaler

array([[ 1.21113647,  0.25843996, -0.04339888, -1.82255983],
       [ 1.21113647,  0.25843996, -0.04339888, -1.82255983],
       [ 1.21113647,  0.25843996, -0.04339888, -1.82255983],
       ...,
       [-2.68776547, -0.87252318,  1.00697603,  0.185672  ],
       [-2.68776547, -0.87252318,  1.00697603,  0.47256226],
       [-2.68776547, -0.87252318,  1.00697603,  0.75945253]])

In [31]:
X2 = pd.DataFrame(p2_scaler)

In [32]:
X2

0         1         2         3
0      1.211136  0.258440 -0.043399 -1.822560
1      1.211136  0.258440 -0.043399 -1.822560
2      1.211136  0.258440 -0.043399 -1.822560
3      1.211136  0.258440 -0.043399 -1.822560
4      1.211136  0.258440 -0.043399 -1.822560
...         ...       ...       ...       ...
40450 -2.687765 -0.872523 -2.144149  0.759453
40451 -2.687765 -0.872523  1.006976 -1.535670
40452 -2.687765 -0.872523  1.006976  0.185672
40453 -2.687765 -0.872523  1.006976  0.472562
40454 -2.687765 -0.872523  1.006976  0.759453

[40455 rows x 4 columns]

In [33]:
X = pd.merge(X1, X2, left_index=True, right_index=True)
X

0_x       1_x       2_x       3_x         4         5         6  \
0      0.425401 -0.106755 -1.542924  0.676434  0.634187  0.649658  0.475015   
1     -1.046615 -0.805221  1.143433 -1.235631 -1.249585 -1.315759 -1.025408   
2     -0.373694 -0.455988  0.695707 -0.150646 -0.203045 -0.225454 -0.335118   
3     -1.004557 -1.084608 -0.199745 -1.137805 -1.144931 -1.244028 -0.979507   
4      1.245524  0.172632 -0.647472  1.290073  1.227226  1.295234  1.239689   
...         ...       ...       ...       ...       ...       ...       ...   
40450 -0.689126 -0.805221  1.143433 -0.568632 -0.656546 -0.698876 -0.665250   
40451  1.476841  2.058492  2.038886  1.298967  1.140014  1.524771  1.305890   
40452  0.236142  3.106192 -0.199745  0.240661  0.180686  0.592274  0.139104   
40453  5.472313  3.525272 -2.438377  3.282178  3.145883  3.920572  5.346435   
40454  1.897417  2.058492 -0.647472  1.539086  1.427813  1.811694  1.699589   

            0_y       1_y       2_y       3_y  
0      1.211136  0.258440 -0.043399 -1.822560  
1      1.211136  0.258440 -0.043399 -1.822560  
2      1.211136  0.258440 -0.043399 -1.822560  
3      1.211136  0.258440 -0.043399 -1.822560  
4      1.211136  0.258440 -0.043399 -1.822560  
...         ...       ...       ...       ...  
40450 -2.687765 -0.872523 -2.144149  0.759453  
40451 -2.687765 -0.872523  1.006976 -1.535670  
40452 -2.687765 -0.872523  1.006976  0.185672  
40453 -2.687765 -0.872523  1.006976  0.472562  
40454 -2.687765 -0.872523  1.006976  0.759453  

[40455 rows x 11 columns]

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(f"X_train: {X_train.shape}, X_test: {X_test.shape}, y_train: {y_train.shape}, y_test: {y_test.shape}")

X_train: (32364, 11), X_test: (8091, 11), y_train: (32364,), y_test: (8091,)


In [ ]:

'''param_grid = {
    'bootstrap': [True],
    'max_depth': [50,80,100],
    'max_features': [3,5,7,9],
    'min_samples_leaf': [1,2,3,4,5],
    'min_samples_split': [4, 6, 8],
    'n_estimators': [50,100, 200, 300]
}

rf = RandomForestRegressor()

grid_search = GridSearchCV(estimator = rf, param_grid = param_grid, 
                          cv = 3, n_jobs = -1, verbose = 2)

grid_search.fit(X_train, y_train)
grid_search.best_params_'''


In [ ]:
#grid_search.best_params_

In [35]:
model = RandomForestRegressor(random_state = 42,
                              n_estimators = 1000,
                               criterion = 'squared_error',
                               max_depth = 20,
                               oob_score = True)

In [36]:
model.fit(X_train, y_train)

/Users/anadeondarza/miniconda3/envs/sklearn-env/lib/python3.10/site-packages/sklearn/utils/validation.py:1858: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


RandomForestRegressor(max_depth=20, n_estimators=1000, oob_score=True,
                      random_state=42)

In [37]:
predictions = model.predict(X_test)
predictions

/Users/anadeondarza/miniconda3/envs/sklearn-env/lib/python3.10/site-packages/sklearn/utils/validation.py:1858: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


array([ 706.64810714, 8233.5816119 , 7717.3296953 , ...,  522.18930493,
       3556.33439904, 2292.44292778])

In [38]:
rmse = mean_squared_error(predictions, y_test, squared=False)
rmse

542.7381418667845

In [39]:
diamantes_predicts = pd.read_csv('/Users/anadeondarza/Desktop/ironhack_data/Todo junto/Data/diamonds_test.csv')
diamantes_predicts

id  carat        cut color clarity  depth  table     x     y     z  \
0          0   0.79  Very Good     F     SI1   62.7   60.0  5.82  5.89  3.67   
1          1   1.20      Ideal     J     VS1   61.0   57.0  6.81  6.89  4.18   
2          2   1.57    Premium     H     SI1   62.2   61.0  7.38  7.32  4.57   
3          3   0.90  Very Good     F     SI1   63.8   54.0  6.09  6.13  3.90   
4          4   0.50  Very Good     F     VS1   62.9   58.0  5.05  5.09  3.19   
...      ...    ...        ...   ...     ...    ...    ...   ...   ...   ...   
13480  13480   0.57      Ideal     E     SI1   61.9   56.0  5.35  5.32  3.30   
13481  13481   0.71      Ideal     I     VS2   62.2   55.0  5.71  5.73  3.56   
13482  13482   0.70      Ideal     F     VS1   61.6   55.0  5.75  5.71  3.53   
13483  13483   0.70  Very Good     F     SI2   58.8   57.0  5.85  5.89  3.45   
13484  13484   0.40      Ideal     I    VVS2   62.4   55.0  4.70  4.73  2.94   

                city  
0          Amsterdam  
1              Surat  
2           Kimberly  
3           Kimberly  
4          Amsterdam  
...              ...  
13480      Amsterdam  
13481  New York City  
13482       Tel Aviv  
13483          Surat  
13484  New York City  

[13485 rows x 11 columns]

In [40]:
diamantes_predicts = diamantes_predicts.drop('id', axis=1)

In [41]:
diamantes_predicts

carat        cut color clarity  depth  table     x     y     z  \
0       0.79  Very Good     F     SI1   62.7   60.0  5.82  5.89  3.67   
1       1.20      Ideal     J     VS1   61.0   57.0  6.81  6.89  4.18   
2       1.57    Premium     H     SI1   62.2   61.0  7.38  7.32  4.57   
3       0.90  Very Good     F     SI1   63.8   54.0  6.09  6.13  3.90   
4       0.50  Very Good     F     VS1   62.9   58.0  5.05  5.09  3.19   
...      ...        ...   ...     ...    ...    ...   ...   ...   ...   
13480   0.57      Ideal     E     SI1   61.9   56.0  5.35  5.32  3.30   
13481   0.71      Ideal     I     VS2   62.2   55.0  5.71  5.73  3.56   
13482   0.70      Ideal     F     VS1   61.6   55.0  5.75  5.71  3.53   
13483   0.70  Very Good     F     SI2   58.8   57.0  5.85  5.89  3.45   
13484   0.40      Ideal     I    VVS2   62.4   55.0  4.70  4.73  2.94   

                city  
0          Amsterdam  
1              Surat  
2           Kimberly  
3           Kimberly  
4          Amsterdam  
...              ...  
13480      Amsterdam  
13481  New York City  
13482       Tel Aviv  
13483          Surat  
13484  New York City  

[13485 rows x 10 columns]

In [42]:
diamantes_predicts["Volumen"] = diamantes_predicts['x']*diamantes_predicts['y']*diamantes_predicts['z']
diamantes_predicts

carat        cut color clarity  depth  table     x     y     z  \
0       0.79  Very Good     F     SI1   62.7   60.0  5.82  5.89  3.67   
1       1.20      Ideal     J     VS1   61.0   57.0  6.81  6.89  4.18   
2       1.57    Premium     H     SI1   62.2   61.0  7.38  7.32  4.57   
3       0.90  Very Good     F     SI1   63.8   54.0  6.09  6.13  3.90   
4       0.50  Very Good     F     VS1   62.9   58.0  5.05  5.09  3.19   
...      ...        ...   ...     ...    ...    ...   ...   ...   ...   
13480   0.57      Ideal     E     SI1   61.9   56.0  5.35  5.32  3.30   
13481   0.71      Ideal     I     VS2   62.2   55.0  5.71  5.73  3.56   
13482   0.70      Ideal     F     VS1   61.6   55.0  5.75  5.71  3.53   
13483   0.70  Very Good     F     SI2   58.8   57.0  5.85  5.89  3.45   
13484   0.40      Ideal     I    VVS2   62.4   55.0  4.70  4.73  2.94   

                city     Volumen  
0          Amsterdam  125.806866  
1              Surat  196.129362  
2           Kimberly  246.878712  
3           Kimberly  145.593630  
4          Amsterdam   81.997355  
...              ...         ...  
13480      Amsterdam   93.924600  
13481  New York City  116.477148  
13482       Tel Aviv  115.898725  
13483          Surat  118.874925  
13484  New York City   65.359140  

[13485 rows x 11 columns]

In [43]:
diamantes_predicts_p1 = diamantes_predicts.drop(["cut", "color", "clarity","city"], axis = 1)
diamantes_predicts_p1

carat  depth  table     x     y     z     Volumen
0       0.79   62.7   60.0  5.82  5.89  3.67  125.806866
1       1.20   61.0   57.0  6.81  6.89  4.18  196.129362
2       1.57   62.2   61.0  7.38  7.32  4.57  246.878712
3       0.90   63.8   54.0  6.09  6.13  3.90  145.593630
4       0.50   62.9   58.0  5.05  5.09  3.19   81.997355
...      ...    ...    ...   ...   ...   ...         ...
13480   0.57   61.9   56.0  5.35  5.32  3.30   93.924600
13481   0.71   62.2   55.0  5.71  5.73  3.56  116.477148
13482   0.70   61.6   55.0  5.75  5.71  3.53  115.898725
13483   0.70   58.8   57.0  5.85  5.89  3.45  118.874925
13484   0.40   62.4   55.0  4.70  4.73  2.94   65.359140

[13485 rows x 7 columns]

In [44]:
scaler = StandardScaler()
p1_scaler_predi = scaler.fit_transform(diamantes_predicts_p1)
p1_scaler_predi

array([[-0.01841187,  0.66950043,  1.12187438, ...,  0.13323602,
         0.17309121, -0.05488267],
       [ 0.85507765, -0.51495701, -0.21919161, ...,  1.01939517,
         0.87078717,  0.86756363],
       [ 1.64334867,  0.3211306 ,  1.56889637, ...,  1.40044361,
         1.40431938,  1.53326171],
       ...,
       [-0.21015347, -0.09691321, -1.1132356 , ..., -0.02627263,
        -0.01843317, -0.18485144],
       [-0.21015347, -2.04778429, -0.21919161, ...,  0.13323602,
        -0.12787567, -0.14581152],
       [-0.84929214,  0.46047853, -1.1132356 , ..., -0.89470861,
        -0.82557163, -0.84779795]])

In [48]:
X1_predi = pd.DataFrame(p1_scaler_predi)

In [49]:
diamantes_p2_predi = diamantes_predicts[["cut", "color", "clarity","city"]]

In [50]:
diamantes_p2_predi

cut color clarity           city
0      Very Good     F     SI1      Amsterdam
1          Ideal     J     VS1          Surat
2        Premium     H     SI1       Kimberly
3      Very Good     F     SI1       Kimberly
4      Very Good     F     VS1      Amsterdam
...          ...   ...     ...            ...
13480      Ideal     E     SI1      Amsterdam
13481      Ideal     I     VS2  New York City
13482      Ideal     F     VS1       Tel Aviv
13483  Very Good     F     SI2          Surat
13484      Ideal     I    VVS2  New York City

[13485 rows x 4 columns]

In [51]:
"""for x in diamantes_p2_predi.columns:
    diamantes_p2_predi[x] = label_encoder.fit_transform(diamantes_p2_predi[x])
diamantes_p2_predi"""

'for x in diamantes_p2_predi.columns:\n    diamantes_p2_predi[x] = label_encoder.fit_transform(diamantes_p2_predi[x])\ndiamantes_p2_predi'

In [52]:
cut_ = {'Very Good':3,'Ideal':4, 'Good':2, 'Premium':5, 'Fair':1}
diamantes_p2_predi['cut'] = diamantes_p2_predi['cut'].map(cut_)
diamantes_p2_predi

/var/folders/nr/c9s62s617y19j9y8cd0wk75c0000gn/T/ipykernel_4527/2941225191.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  diamantes_p2_predi['cut'] = diamantes_p2_predi['cut'].map(cut_)


cut color clarity           city
0        3     F     SI1      Amsterdam
1        4     J     VS1          Surat
2        5     H     SI1       Kimberly
3        3     F     SI1       Kimberly
4        3     F     VS1      Amsterdam
...    ...   ...     ...            ...
13480    4     E     SI1      Amsterdam
13481    4     I     VS2  New York City
13482    4     F     VS1       Tel Aviv
13483    3     F     SI2          Surat
13484    4     I    VVS2  New York City

[13485 rows x 4 columns]

In [53]:
color_ = {'D':2,'H':5, 'J':7, 'I':6, 'E':1, 'F':3, 'G':4}
diamantes_p2_predi['color'] = diamantes_p2_predi['color'].map(color_)

/var/folders/nr/c9s62s617y19j9y8cd0wk75c0000gn/T/ipykernel_4527/2870411648.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  diamantes_p2_predi['color'] = diamantes_p2_predi['color'].map(color_)


In [54]:
clarity_ = {'SI2':8,'VVS2':2, 'VVS1':3, 'IF':1, 'SI1':6, 'I1':7, 'VS1':4, 'VS2':5 }
diamantes_p2_predi['clarity'] = diamantes_p2_predi['clarity'].map(clarity_)

/var/folders/nr/c9s62s617y19j9y8cd0wk75c0000gn/T/ipykernel_4527/4228109124.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  diamantes_p2_predi['clarity'] = diamantes_p2_predi['clarity'].map(clarity_)


In [55]:
city_ = {'Amsterdam':1,'Zurich':2, 'Las Vegas':3, 'New York City':4, 'Paris':5, 'Tel Aviv':6, 'Dubai':7, 'Kimberly':8, 'Surat':9,'Antwerp':10, 'Madrid':11, 'London':12, 'Luxembourg':13}
diamantes_p2_predi['city'] = diamantes_p2_predi['city'].map(city_)

/var/folders/nr/c9s62s617y19j9y8cd0wk75c0000gn/T/ipykernel_4527/2214678504.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  diamantes_p2_predi['city'] = diamantes_p2_predi['city'].map(city_)


In [56]:
scaler = StandardScaler()
p2_scaler_predi = scaler.fit_transform(diamantes_p2_predi)
p2_scaler_predi

array([[-0.74621338, -0.29657963,  0.48882451, -1.81560393],
       [ 0.22471362,  1.9683935 , -0.56266672,  0.4682971 ],
       [ 1.19564062,  0.83590694,  0.48882451,  0.18280947],
       ...,
       [ 0.22471362, -0.29657963, -0.56266672, -0.38816579],
       [-0.74621338, -0.29657963,  1.54031575,  0.4682971 ],
       [ 0.22471362,  1.40215022, -1.61415796, -0.95914105]])

In [57]:
X2_predi = pd.DataFrame(p2_scaler_predi)
X2_predi

0         1         2         3
0     -0.746213 -0.296580  0.488825 -1.815604
1      0.224714  1.968394 -0.562667  0.468297
2      1.195641  0.835907  0.488825  0.182809
3     -0.746213 -0.296580  0.488825  0.182809
4     -0.746213 -0.296580 -0.562667 -1.815604
...         ...       ...       ...       ...
13480  0.224714 -1.429066  0.488825 -1.815604
13481  0.224714  1.402150 -0.036921 -0.959141
13482  0.224714 -0.296580 -0.562667 -0.388166
13483 -0.746213 -0.296580  1.540316  0.468297
13484  0.224714  1.402150 -1.614158 -0.959141

[13485 rows x 4 columns]

In [58]:
X = pd.merge(X1_predi, X2_predi, left_index=True, right_index=True)
X

0_x       1_x       2_x       3_x         4         5         6  \
0     -0.018412  0.669500  1.121874  0.075022  0.133236  0.173091 -0.054883   
1      0.855078 -0.514957 -0.219192  0.964007  1.019395  0.870787  0.867564   
2      1.643349  0.321131  1.568896  1.475847  1.400444  1.404319  1.533262   
3      0.215939  1.435914 -1.560258  0.317472  0.345914  0.487738  0.204668   
4     -0.636246  0.808848  0.227830 -0.616411 -0.575691 -0.483564 -0.629548   
...         ...       ...       ...       ...       ...       ...       ...   
13480 -0.487114  0.112109 -0.666214 -0.347022 -0.371875 -0.333080 -0.473094   
13481 -0.188849  0.321131 -1.113236 -0.023755 -0.008549  0.022608 -0.177264   
13482 -0.210153 -0.096913 -1.113236  0.012164 -0.026273 -0.018433 -0.184851   
13483 -0.210153 -2.047784 -0.219192  0.101960  0.133236 -0.127876 -0.145812   
13484 -0.849292  0.460479 -1.113236 -0.930699 -0.894709 -0.825572 -0.847798   

            0_y       1_y       2_y       3_y  
0     -0.746213 -0.296580  0.488825 -1.815604  
1      0.224714  1.968394 -0.562667  0.468297  
2      1.195641  0.835907  0.488825  0.182809  
3     -0.746213 -0.296580  0.488825  0.182809  
4     -0.746213 -0.296580 -0.562667 -1.815604  
...         ...       ...       ...       ...  
13480  0.224714 -1.429066  0.488825 -1.815604  
13481  0.224714  1.402150 -0.036921 -0.959141  
13482  0.224714 -0.296580 -0.562667 -0.388166  
13483 -0.746213 -0.296580  1.540316  0.468297  
13484  0.224714  1.402150 -1.614158 -0.959141  

[13485 rows x 11 columns]

In [59]:
final = model.predict(X)
final

/Users/anadeondarza/miniconda3/envs/sklearn-env/lib/python3.10/site-packages/sklearn/utils/validation.py:1858: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


array([3008.09498304, 5461.93166667, 9986.98111416, ..., 3065.89855672,
       2180.39344304,  809.57039286])

In [60]:
final = pd.DataFrame(final).rename(columns = {0:'price'})
final.index.names = ['id']
final

price
id                
0      3008.094983
1      5461.931667
2      9986.981114
3      4037.226788
4      1669.618137
...            ...
13480  1672.091051
13481  2326.494763
13482  3065.898557
13483  2180.393443
13484   809.570393

[13485 rows x 1 columns]

In [61]:
XYZ_hand = final.to_csv('XYZ_hand.csv')